### ISSUE TITLE
`go install` doesn't work

### ISSUE THREAD

**Issue by verlok** [xavidop/codelab-template#3]
**Describe the bug**
In the readme.md file, you say to install `claat` we need to use `go install...`.
That doesn't work.

**To Reproduce**
1. Open Terminal
2. Enter `go` and press enter
3. See error

**Expected behavior**
The readme should state that Go is a requirement, and that can be downloaded from here https://go.dev/dl/

**Comment by xavidop** [comment]
sure, I assumed that. Let me add it

**Comment by xavidop** [comment]
solved in https://github.com/xavidop/codelab-template/pull/4
